### ISSUE TITLE
https 설정 예시

### ISSUE THREAD

**Issue by ray5273** [ray5273/comentario#8]
```
version: '3'

services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: comentario
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  app:
    image: ray5273/comentario:latest
    command:
    - "--scheme=https"
    - "--tls-cert=/etc/letsencrypt/live/ray5273.duckdns.org/fullchain.pem"
    - "--tls-key=/etc/letsencrypt/live/ray5273.duckdns.org/privkey.pem"
    - "-v"
    environment:
      BASE_URL: https://ray5273.duckdns.org:8443/
      SECRETS_FILE: "/secrets.yaml"
      TLS_PORT: 8443
      TLS_HOST: 0.0.0.0
    ports:
      - "8443:8443"
    volumes:
      - ./secrets.yaml:/secrets.yaml:ro
      - /etc/letsencrypt/:/etc/letsencrypt/:ro
 ```
